-- TODO: [Feature not implemented yet]
-- TODO: Swapping a team, is, COMPLETELY bugged out ... :/ ... Debug it!


--[[
    init.lua
    Created: 07/17/2025 00:27:45
    Description: Autogenerated script file for the map advanced_camp.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'origin.menu.team.AssemblySelectMenu'
require 'rescue_team_outpost.menu.ScriptableMultiPageOptionsMenu'
require 'rescue_team_outpost.menu.ZoneMenu'
require 'rescue_team_outpost.common'

-- If imported MOD middle-gameplay, init scriptvars
if not SV.rescue_team_outpost then require 'rescue_team_outpost.scriptvars' end


-- Package names
local advanced_camp = {}
----------------

--[[ Available objects
  
  -- Entrances / Exits
    Entrance_South
    Exit_South
    BlockNorthArea
  
  -- Shops
    Shop1
    Shop1Char
    Shop2
    Shop2Char
    Shop3
    Shop3Char
    
    Shop4
    Shop4Char
    Shop5
    Shop5Char
    Shop6
    Shop6Char
    Shop7
    Shop7Char
]]

local InitHooks = CURMAPSCR.InitHooks
table.insert(InitHooks, function(map)
	DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> Init_advanced_camp -> Rescue Team Outpost")

	local Assistants = {
		"lucario",
		"gogoat",
		"arcanine",
		"donphan",
		"decidueye"
	}
	local Assistant = Assistants[math.random(#Assistants)]
	
	local Char2Shop = CH("Shop2Char") --[[ GroundChar ]]
	-- species / form / skin / gender
	Char2Shop.Data.BaseForm = RogueEssence.Dungeon.MonsterID(Assistant, 0, "normal", COMMON.NumToGender(1))
	
	rto_mod_init()
	
	GROUND:Unhide("Shop2Char")
end)

function advanced_camp.Shop2_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  
	local teamLimit = SV.rescue_team_outpost.settings.minimum_assembly
	
	rto_outpost_intro()
	rto_check_conditions()
	
  if SV.rescue_team_outpost.outpost_status == 0 then
		
  elseif SV.rescue_team_outpost.outpost_status == 1 then
		rto_condition_assembly_count_failed()
		
  elseif SV.rescue_team_outpost.outpost_status >= 2 then
    rto_outpost()
		
  end
end

function rto_mod_init()
	rto_uids.init_all()
	
	
	SV.rescue_team_outpost.introduced = true
	
	-- SV.rescue_team_outpost.teams = {}
	
	-- local random_zone_id = 'tropical_path'
	-- PrintInfo("rto_zones.zone_exists(random_zone_id): " .. (rto_zones.zone_exists(random_zone_id) and 'Y' or 'N'))
	-- PrintInfo("rto_zones.zone_summary_toString(rto_zones.zone_summary(random_zone_id)): " .. rto_zones.zone_summary_toString(rto_zones.zone_summary(random_zone_id)))
	-- PrintInfo("rto_zones.ids(): " .. COMMON.print_r(rto_zones.ids(), 1))
	-- PrintInfo("rto_zones.names(): " .. COMMON.print_r(rto_zones.names(), 1))
	-- PrintInfo("rto_zones.debug_zone_data_segments_steps(random_zone_id): " .. rto_zones.debug_zone_data_segments_steps(random_zone_id))
	-- PrintInfo("rto_zones.zone_data(random_zone_id): " .. COMMON.print_r(rto_zones.zone_data(random_zone_id), 1))
	-- PrintInfo("rto_zones.zone_data_segments(random_zone_id): " .. COMMON.print_r(rto_zones.zone_data_segments(random_zone_id), 1))
	
	-- rto_teams.new_quest_menu(SV.rescue_team_outpost.teams.B)
end

function rto_outpost_intro()
	local teamLimit = SV.rescue_team_outpost.settings.minimum_assembly
	if SV.rescue_team_outpost.introduced == false then
		UI:SetSpeaker(CH('Shop2Char'))
		UI:WaitShowDialogue("Welcome adventurer!")
		UI:WaitShowDialogue("We are the Rescue Team Outpost(TM), teams larger than " .. teamLimit .. " members can register with us!")
		UI:WaitShowDialogue("We help teams orginize their dungeon expeditions")
		
		SV.rescue_team_outpost.introduced = true
	end
end

function rto_check_conditions()
	local teamLimit = SV.rescue_team_outpost.settings.minimum_assembly
	if GAME:GetPlayerAssemblyCount() <= teamLimit then
		SV.rescue_team_outpost.outpost_status = 1
	else
		SV.rescue_team_outpost.outpost_status = 2
	end
end

function rto_condition_assembly_count_failed()
	UI:SetSpeaker(CH('Shop2Char'))
	UI:WaitShowDialogue("Adventurer, for safetly reasons for a team to split it must count more than " .. teamLimit .. " members.")
	UI:WaitShowDialogue("Come back when you are more, we'll be waiting!")
end

function rto_restriction_pass_new_team_member_count(member_count)
	if member_count < SV.rescue_team_outpost.settings.team_members_min then
		return false
	end
	if member_count > SV.rescue_team_outpost.settings.team_members_max then
		return false
	end
	return true
end

function rto_teams_count_check()
	if rto_scriptvars.Team.count() <= 1 then
		UI:WaitShowDialogue("You dont have another team registered yet!")
		UI:WaitShowDialogue("Start by making another one")
		return false
	end
	return true
end

function rto_main_menu()
	while true do
		
		local qt_enabled = rto_scriptvars.Team.count() > 1 and #rto_teams.questing_teams() > 0
		local ct_enabled = rto_scriptvars.Team.count() > 1
		
		local choices = {}
		table.insert(choices, "New Team")
		table.insert(choices, "View Teams")
		table.insert(choices, {"Questing Teams", qt_enabled})
		table.insert(choices, {"Change Team", ct_enabled})
		table.insert(choices, "Back")
		
		local choice_i = COMMON.show_choice_menu(STRINGS:Format("Set your teams smartly!"), choices)
		local choice = choices[choice_i]
		local choice_str = (type(choice) == "table" and {choice[1]} or {choice})[1]
		
				if choice_str == "Back" 					then 	return
		elseif choice_str == "New Team" 			then 	rto_teams.edit_menu()
		elseif choice_str == "View Teams" 		then	rto_teams.view_all_menu()
		elseif choice_str == "Questing Teams" then	rto_teams.view_questing_menu()
		elseif choice_str == "Change Team" 		then	rto_teams.set_active_menu()
		end
		COMMON.stopwatch_stats()
	end
end

function rto_outpost()
	rto_scriptvars.Team.sync_active_team()
	
  local state = 0
  UI:SetSpeaker(CH('Shop2Char'))
	
	while state > -1 do
		
		if state == 0 then
			
			local result = COMMON.show_choice_menu(STRINGS:Format("Ready for more expeditions?!"), {
				"Teams",
				"...",
				"Bye!",
			})
			
			if result == 2 then
				-- local bag_count = GAME:GetPlayerBagCount() + GAME:GetPlayerEquippedCount()
				-- if bag_count > 0 then
				-- 	... RtoFlow()
				-- else
				-- 	UI:WaitShowDialogue("Boy don't cha play wi-me... Yer pockets are empty!")
				-- end
			
      elseif result == 1 then
				rto_main_menu()
        
			elseif result == 3 then
				UI:WaitShowDialogue("Fare-well!")
				state = -1
			end
		end
		
	end
end

return advanced_camp